server:
  port: 8060

spring:
  application:
    name: hystrix

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: ["health","info","hystrix.stream"]

#hystrix:
#  dashboard:
#    proxy-stream-allow-list:  "192.168.0.181"